services:
  - type: web
    name: anapec-backend
    repo: https://github.com/YRAJJAF/anapec-platform-fullstack.git
    branch: main
    root: backend
    buildCommand: npm install && npm run build
    startCommand: node dist/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
    postgres:
      version: "15"

  - type: web
    name: anapec-frontend
    repo: https://github.com/YRAJJAF/anapec-platform-fullstack.git
    branch: main
    root: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://anapec-backend.onrender.com/api/v1